config/routes.rb
Rails.application.routes.draw do
  resources :user
  resources :gossips
  resources :sessions
  #get 'gossips/:id',to:'gossips#show', as: "gossips"
  #get 'gossips/', to: 'gossips#new', 
  # get '/user/:id', to: 'user#show',as: "user"
  
  get '/team', to: 'index#team'
  get '/contact', to: 'index#contact'
  get '/welcome/:name', to: 'index#welcome'
  root 'index#home'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  
  belongs_to :user ,optional: true
  delegate :first_name, to: :user, allow_nil: true, prefix: true
  has_many :taggers
  has_many :tags, through: :taggers
end
#user,optional: true

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggers
  has_many :gossips, through: :taggers
end

app/models/tagger.rb
class Tagger < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
   #probleme seed
  belongs_to :city,optional: true
  has_many :gossips 
  belongs_to :city, optional: true
  has_many :sent_messages, foreign_key: 'sender', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient', class_name: "PrivateMessage"
  validates :password, 
  presence: true, 
  length: { minimum: 1 }
  has_secure_password

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_users, :logged_in?,:log_in
def current_users
   @current_users ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
  !current_users
end

def require_user
  if !logged_in?
    flash[:alert] = "You must be logged in to perform that action."
    redirect_to root_path
  end
end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: %i[ create new ]
  def edit 
    
  end
  def show
    # @gossip = Gossip.all.find_by(id:params[:id])
    @gossip = Gossip.find(params[:id])
  end
  def new
    
  end
  
    def create
       
      
      @gossip = Gossip.new(title:params[:title], content:params[:content], user:current_users)
      if @gossip.save
        redirect_to root_path
       
      else 
        redirect_to new_gossip_path
        
      end
      
    end  
      # current_users
    
     def gossip_params
      params.permit(:title, :content, :user_id)
    end
    def set_gossip
      if !current_users
        redirect_to root_path
      end
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    @gossips = Gossip.all
    @user = User.all
  end
  def team

  end
  def contact

  end
  def welcome
    @gossips = Gossip.all
  end 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    user = User.new
  end
  
  def create
    user = User.find_by(email:params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # log_in(user)
      flash[:notice] = "You login successfully!"
      redirect_to root_path
    else 
      flash.now[:alert] = 'Invalid email/password combinaison'
    render 'new'
    end
  end
  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(first_name:params[:first_name], last_name:params[:last_name], 
      age:params[:age], description:params[:description], email:params[:email], 
      password:params[:password])
      
    if @user.save
      flash[:notice] = "You have created your account!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indexcontroller_helper.rb
module IndexcontrollerHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/new.html.erb
<html>
  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 
    <div class="page content col-7">
      <%= form_tag url_for(action: 'create'), method: "post" do %>
        <div class="form-group">
        <%= label_tag 'Title', name = 'Title', class: 'font-weight-bold'%>
        <%= text_field_tag 'title', nil, placeholder: 'Enter a title', class: 'form-control'%>
        <small id="emailHelp" class="form-text text-muted">3 caracters minimum and 14 caracters maximum.</small>
        </div>
        
        <div class="form-group">
        <%= label_tag 'Content', name = 'Content' , class: 'font-weight-bold'%>
        <%= text_area_tag 'content', nil, rows: 6, placeholder: 'Write your gossip...', class: 'form-control'%>
        </div>
        <br><br>

        <%= submit_tag "Create Post", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </body>
</html>
© 2021 GitHub, Inc.

app/views/gossips/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 
  <p style="font-size: 22px"><u><b>Gossip n° <%=@gossip.id%></b></u></p>
  

  <div class="content">
    <div class="section">
      <p>
      author:<%=  @gossip.user.try(:first_name) %></p><%= link_to "clique ici", user_path(@gossip.id) %>
        
      </p>
      <p><b>Title:</b> <%= @gossip.title %></p>
      <p><b>Content:</b> <%= @gossip.content %></p>
       <%= link_to "clique ici", new_gossip_path %>
     
  </div>

</div>

app/views/index/contact.html.erb
<!--Section: Contact v.2-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 
<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
       

    </div>

</section>
<!--Section: Contact v.2-->

app/views/index/home.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 
<div class="wrapping">

<div class="jumbotron jumbotron-fluid text-center" style="background-image: url(https://i.pinimg.com/564x/7e/12/94/7e1294d5fdbd33d10726312ba874dd43.jpg)">
  <div class="box mx-auto">
    <h1 class="title"><b>THE GOSSIP PROJECT</b></h1>
    <p class="lead"><b>This Gossip Project allows users to post, comment and like gossips...</b></p>
     
  </div>
</div>
<div class="container text-center">
  <div class="page">
    <h4><u>Juicy list of Gossips:</u></h4>
    <div class="btn btn-outline-dark btn-lg link_no_decoration"><%= link_to "Crée un potin", new_gossip_path %></div>
  </div>
  <br>  

  
<div class="row">
<% Gossip.all.each_with_index do |gossip,i| %>
  <div class="col-sm-4 mx-auto pt-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= gossip.title %></h5>
        <p class="card-text"><%= gossip.content %></p>
           <div class="btn btn-outline-dark btn-lg link_no_decoration"><%= link_to "Voir le potin", gossip_path(gossip.id) %></div><br>

        <%= gossip.user.try(:first_name) %></p>
     
        
        <%  if current_users.try(:first_name)==gossip.user.try(:first_name) %>
          
    
        <div class = "btn btn-outline-dark btn-lg link_no_decoration"><%= link_to "Edit", edit_gossip_path(gossip.id)%></div>
            
      <% end %>  
      </div>
    </div>
  </div>
<%end%>
</div>

app/views/index/team.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 
<div class="wrapping">
  <div class="text-center">
  <h1 >Meet our great team!</h1><br>
  <h2 style="color: #eeb4ba;">THE GOSSIP POLICE</h2>
  </div>

  <div class="page content">
    <div class="row text-center">
      <div class="card" style="width: 20rem;">
        <div class="card-body">
          <h4> Bubble<br>
          <b>Powerpuff</b></h4><br>
          <h3>UI/UX Designer</h3>
          <p style="font-size:100px">&#127912;</p>
          <h5><b>Description:</b></h5>
          <p class="card-text">Hey! My name is Bubble, I am sweet and I really love Gossip as long as they are not mean because I am really sensitve.</p>
          <h5><b>Send me a mail:</b></h5>
          <a href="mailto:gossip@gossipproject.org">bubble@gossipproject.org</a>
        </div>
      </div>

      <div class="card" style="width: 20rem;">
        <div class="card-body ">
          <h4> Blossom<br>
          <b>Powerpuff</b></h4><br>
          <h3>CEO</h3>
          <p style="font-size:100px">&#128188;</p>
          <h5><b>Description:</b></h5>
          <p class="card-text">Hey my name is Blossom, I am the CEO of The Gossip Project. I am really proud of my team and i really love gossip! </p>
          <h5><b>Send me a mail:</b></h5>
          <a href="mailto:gossip@gossipproject.org">blossom@gossipproject.org</a>
        </div>
      </div>

      <div class="card" style="width: 20rem;">
        <div class="card-body">
        <h4> Buttercup<br>
          <b>Powerpuff</b></h4><br>
          <h3>CTO</h3>
          <p style="font-size:100px">&#128187;</p>
          <h5><b>Description:</b></h5>
          <p class="card-text">Hey, I am Buttercup, I am the CTO of The Gossip Project. I put a lots of effort into this web app. I hope you'll like it!</p>
          <h5><b>Send me a mail:</b></h5>
          <a href="mailto:gossip@gossipproject.org">buttercup@gossipproject.org</a>
        </div>
      </div>
    </div><br><br>

    <div class="fixed-bottom" style="text-align: center;">
      <p>© The Gossip Project</p>
    </div>
  </div>
</div>

app/views/index/welcome.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="#">team</a>
      <a class="nav-item nav-link" href="#">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 

<div class="container text-center">
<h1>Hello <%= params[:name].capitalize %></h1>
<h2><em>Welcome to The Gossip Project!</em></h2>
<div><h3><u>Juicy list of Gossips:</u></h3></div><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/new.html.erb
<div class="page content col-5">
  <h1>Create an account:</h1><br>

  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
      <%= label_tag 'First Name', name = 'First Name', class: 'font-weight-bold'%>
      <%= text_field_tag 'first_name', nil, placeholder: 'Enter your first name', class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= label_tag 'Last Name', name = 'Last Name', class: 'font-weight-bold'%>
      <%= text_field_tag 'last_name', nil, placeholder: 'Enter your last name', class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= label_tag 'Age', name = 'Age', class: 'font-weight-bold'%>
      <%= text_field_tag 'age', nil, placeholder: 'Your age', class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= label_tag 'Description', name = 'Description', class: 'font-weight-bold'%>
      <%= text_area_tag 'description', nil,rows: 3, placeholder: 'Describe yourself in a few words', class: 'form-control'%>
      <small id="emailHelp" class="form-text text-muted">500 caracters max.</small>
    </div>

    <div class="form-group">
      <%= label_tag 'Email', name = 'Email', class: 'font-weight-bold'%>
      <%= text_field_tag 'email', nil, placeholder: 'Enter your email adress', class: 'form-control'%>
      <small id="emailHelp" class="form-text text-muted">Must be a valid email adress.</small>
    </div>

    <br>

    <div class="form-group">
      <%= label_tag 'Password', name = 'Password' , class: 'font-weight-bold'%>
      <%= password_field_tag 'password', nil, placeholder: 'Choose a password', class: 'form-control'%>
      <small id="emailHelp" class="form-text text-muted">Password must contain as least 6 caracters.</small>
    </div>

    <br>


   

    <%= submit_tag "Submit", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/user/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="/">Home 
      <a class="nav-item nav-link" href="team">team</a>
      <a class="nav-item nav-link" href="contact">contact</a>
      <%# <% if current_users %>  
      <% if logged_in? %>
         <a class="nav-link nav-item" href="<%= new_user_path %>">sign_in</a>
      
         <a class="nav-link nav-item" href="<%= new_session_path %>">session</a>
      
      <% else %>
         
         <a class="nav-link nav-item"><%=  link_to "Log out",  logout_path, method: "delete" %> </a> 
        
      <% end %>     
    </div>
  </div>
</nav>
 


<div class="page content">
  <p style="font-size: 22px"><u><b>Profile of <%= @user.first_name%></b></u></p><br>
  <p><b> First Name: </b><%= @user.first_name%></p>
  <p><b> Last Name: </b><%= @user.last_name%></p>
  <p><b> Email: </b><%= @user.email%></p>
  <p><b> Age: </b><%= @user.age%></p>
  <p><b> City: </b>
  <p><b> Description: </b><%= @user.description%></p>
  <p class="datetime"><em><%= @user.updated_at %><em></p>
</div>